# Generated by Django 5.2.5 on 2025-08-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='contnt',
        ),
    ]
